new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from scraped import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('scraped.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scraped/urls.py
from django.urls import path
from .views import home_view, jobDetails

app_name='scraped'
urlpatterns = [
    path('',home_view, name= 'home_View'),
    path('job/<id>/', jobDetails, name="job_details"),

]

scraped/models.py
from django.db import models


# Create your models here.
class Details(models.Model):
    title = models.CharField(max_length=100, null=True, blank=True)
    thumbnail_img = models.CharField(max_length=200, blank=True, null=True)

    created_on = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        if self.title == None:
            return "ERROR-CUSTOMER NAME IS NULL"
        return str(self.title)


class image(models.Model):
    author = models.ForeignKey(Details, on_delete=models.CASCADE, related_name='images')
    # content = models.TextField()
    image = models.CharField(max_length=200, blank=True, null=True)
    def __str__(self):
        if self.author == None:
            return "ERROR-CUSTOMER NAME IS NULL"
        return str(self.author)


class Video(models.Model):
    author = models.ForeignKey(Details, on_delete=models.CASCADE, related_name='videos')
    video = models.CharField(max_length=200, blank=True, null=True)
    def __str__(self):
        if self.author == None:
            return "ERROR-CUSTOMER NAME IS NULL"
        return str(self.author)

scraped/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, redirect

from scraped.models import Details,image,Video


def home_view(request):
    page_no = request.GET.get('page', 1)

    works = Details.objects.all().order_by('-id')
    # restaurents = Restaurents.objects.all().order_by('-avarage_ratings')
    paginator = Paginator(works, 20)
    try:
        j = paginator.page(page_no)

    except PageNotAnInteger:
        j = paginator.page(1)

    except EmptyPage:
        j = paginator.page(paginator.num_pages)
    context = {}
    context['jobs']=j
    return render(request, 'index.html', context)


def jobDetails(request, id):
    try:
        try:
            im = image.objects.filter(author=Details.objects.get(id=id))
        except image.DoesNotExist:
            pass
        try:
            vi = Video.objects.filter(author=Details.objects.get(id=id))
        except Video.DoesNotExist:
            pass
    except Details.DoesNotExist:
        return redirect('index')

    context = {
        "images": im,
        "videos":vi

    }
    return render(request, 'jobDetails.html', context)

templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <title>JOBS</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <style>
        .nav-item:hover{
            background-color: skyblue;

            border-radius: 5px;
        }
        .nav-item:hover > a{
            color: white !important;
        }
        .divv {
    text-align:right;
}
    </style>
</head>

<body>
  <nav class="headerNav">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link active" href="home.html">
    <img src="img/fedup logo.jpg" data-visited="true"/>
    </a>
    </li>
    </ul>
    <center>
    <ul class="navjustify-content-center">
      <li class="nav-item">
        <a class="nav-link active" href="home.html">Latest</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="jobscard.html">Popular</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="collection.html">Hot</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="tags.html">Trending</a>
      </li>
    </ul>
    </center>
    <ul class="navjustify-content-end">
    
    </nav>
       <section class="content-wrapper">
    <div class="content">
      <center>
    <div class="inlineHeader">
      
    <h1 class="inlineHeader__title">For All Fans</h1><br>
    <h2 class="inlineHeader__subTitle">Find all Content here</h2>
    </div></center>
    <div class="searchForm" data-behavior="search" data-controller="search-form" data-search-form-since-filter="1607147442">
    <div class="searchForm__box">
    <div class="searchForm__section searchForm__section--primary">
    <div class="searchForm__section__label">What job are you looking for?</div>
    <div class="searchForm__section__input">
    <div id="foobar">
      <div class="ais-SearchBox">
      <form action="" role="search" class="ais-SearchBox-form" novalidate="">
      <input class="ais-SearchBox-input searchField__input" type="search" placeholder="Search for job title, skills, startups…" autofocus="true" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" maxlength="512">
      <button class="ais-SearchBox-submit" type="submit" title="Submit the search query." hidden="">
      <svg class="ais-SearchBox-submitIcon" xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 40 40"> 
      <path d="M26.804 29.01c-2.832 2.34-6.465 3.746-10.426 3.746C7.333 32.756 0 25.424 0 16.378 0 7.333 7.333 0 16.378 0c9.046 0 16.378 7.333 16.378 16.378 0 3.96-1.406 7.594-3.746 10.426l10.534 10.534c.607.607.61 1.59-.004 2.202-.61.61-1.597.61-2.202.004L26.804 29.01zm-10.426.627c7.323 0 13.26-5.936 13.26-13.26 0-7.32-5.937-13.257-13.26-13.257C9.056 3.12 3.12 9.056 3.12 16.378c0 7.323 5.936 13.26 13.258 13.26z">
        
      </path> 
      </svg>
    </button>
    <button class="ais-SearchBox-reset" type="reset" title="Clear the search query." hidden=""><svg class="ais-SearchBox-resetIcon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="10" height="10"> 
      <path d="M8.114 10L.944 2.83 0 1.885 1.886 0l.943.943L10 8.113l7.17-7.17.944-.943L20 1.886l-.943.943-7.17 7.17 7.17 7.17.943.944L18.114 20l-.943-.943-7.17-7.17-7.17 7.17-.944.943L0 18.114l.943-.943L8.113 10z">
        </path> 
      </svg>
       </button>
       <span class="ais-SearchBox-loadingIndicator" hidden="">
         <svg class="ais-SearchBox-loadingIcon" width="16" height="16" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#444"> 
           <g fill="none" fillrule="evenodd"> 
             <g transform="translate(1 1)" strokewidth="2"> 
               <circle strokeopacity=".5" cx="18" cy="18" r="18">
                 
               </circle> 
               <path d="M36 18c0-9.94-8.06-18-18-18"> 
                 <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite">
                   
                 </animateTransform> 
               </path> 
               </g> 
             </g>
           </svg>
         </span>
       </form>
    </div>
    </div>
    </div>
    </div>
    
<section class="content-wrapper">
                        <div class="content content--unpadded">
                            {% for job in jobs %}


                            <div class="jobCard row" data-action="click->clickable#open" data-clickable-target="_blank"
                                data-clickable-url="/art-director-design-at-procore-4" data-controller="clickable">
                                <div class="jobCard__details col-12">
                                <img src='{{ job.thumbnail_img }}'>

                                    <br>
                                    <div class="jobCard__details__ultra col-8">

                                       <a class=""
                                            href="{% url 'scraped:job_details' id=job.id %}">{{ job.title }}</a>


                                        </div>


                                    </div>
                                </div>

                            </div>

                            {% endfor %}


                        </div>
                    </section>
                    <div class="pagination col-12 col-sm-4 justify-content-center">
            <nav aria-label="Page navigation example">
              <ul class="pagination">
                  {% if jobs.has_previous %}
                    <li class="page-item ">
                      <a class="page-link btn btn-active btn-primary" href="?page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    <li class="page-item "><a class="page-link btn btn-active btn-primary" href="?page={{ jobs.previous_page_number }}">{{ jobs.previous_page_number }}</a></li>
                  {% endif %}
                  <li class="page-item "><div class="current page-link">{{ jobs.number }}</div></li>

                  {% if jobs.has_next %}
                    <li class="page-item "><a class="page-link btn btn-active btn-primary" href="?page={{ jobs.next_page_number }}">{{ jobs.next_page_number}}</a></li>
                    {% if jobs.next_page_number != jobs.paginator.num_pages %}
                        <li class="page-item ">
                          <a class="page-link btn btn-active btn-primary" href="?page={{ jobs.paginator.num_pages }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                          </a>
                        </li>
                    {% endif %}
                  {% endif %}
              </ul>
            </nav>
        </div>


</body>

</html>

templates/jobDetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hi
{% for i in images %}
<img src='{{ i.image }}'>
{% endfor %}
{% for v in videos %}
<video width="320" height="240" controls>
  <source src='{{ v.video }}' type="video/mp4">
  <source src='{{ v.video }}' type="video/ogg">
  Your browser does not support the video tag.
</video>
{% endfor %}
</body>
</html>